name: Publish Docs to Centralized Documentation
description: Composite action to publish docs from a source repository to a centralized Documentation repository.
inputs:
  documentation_repository:
    description: 'Documentation repository in the format owner/repo'
    required: true
  documentation_pat:
    description: 'Personal Access Token with repo access'
    required: true
  target_directory:
    description: 'Name of the target directory in the Documentation repository (e.g. Infrastructure)'
    required: true
  source_directory:
    description: 'Path to the docs directory to publish from'
    required: true
  documentation_checkout_path:
    description: 'Directory path where the documentation repository will be checked out'
    required: true
    default: '.documentation'
runs:
  using: composite
  steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4 

    - name: Checkout Documentation Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.documentation_repository }}
        token: ${{ inputs.documentation_pat }}
        path: ${{ inputs.documentation_checkout_path }}

    - name: Copy docs to Documentation Repository 
      shell: bash
      run: |
        mkdir -p ${{ inputs.documentation_checkout_path }}/docs/${{ inputs.target_directory }}
        rsync -av --delete ${{ inputs.source_directory }}/ ${{ inputs.documentation_checkout_path }}/docs/${{ inputs.target_directory }}/
      
    - name: Commit and push changes 
      shell: bash
      working-directory: ${{ inputs.documentation_checkout_path }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        
        git add -A
        git commit -m "Run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        git push