name: Restart kubernetes deployment through ArgoCD API
description: This action can restart a deployment / all deployments inside a ArgoCD application

inputs:
  install:
    description: Install ArgoCD
  cluster:
    description: ArgoCD cluster name that the application belongs to
  application:
    description: ArgoCD application that the deployment belongs to
  kind:
    description: ArgoCD resource type
    default: Deployment
  argocd-server:
    description: ArgoCD Server domain
    required: true
  argocd-auth-token:
    description: ArgoCD auth token
    required: true

runs:
  using: composite
  steps:
  - name: Install ArgoCD
    shell: bash
    if: ${{ inputs.install == 'true' }}
    env:
      ARGOCD_SERVER: ${{ inputs.argocd-server }}
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd-auth-token }}
    run: |
      sudo curl -sSL -o /usr/bin/argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64
      sudo chmod +x /usr/bin/argocd

  - name: Restart deployments
    shell: bash
    env:
      ARGOCD_SERVER: ${{ inputs.argocd-server }}
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd-auth-token }}
    run: argocd app actions run ${{ inputs.cluster }}/${{ inputs.application }} restart --kind ${{ inputs.kind }}
