name: 'Dependency Check'
description: 'Github action to execute dependency check with BOM generation'
inputs:
  project:
    description: 'The project name'
    required: true
  path:
    description: 'The path to the project'
    required: true  
  format:
    description: "The report format(s). Example: 'XML CycloneDX'."
    required: true
  out:
    description: 'The output directory'
    required: false 
    default: 'reports'
  args:
    description: 'The arguments to pass to the dependency check'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run OWASP Dependency-Check (XML only)
      shell: bash
      run: |
        IMAGE="owasp/dependency-check-action:latest"

        docker run --rm \
          -v ${{ github.workspace }}:/src \
          $IMAGE \
          --project "${{ inputs.project }}" \
          --scan "/src/${{ inputs.path }}" \
          --out "/src/${{ inputs.out }}" \
          --noupdate \
          --format XML \
          ${{ inputs.args }}
          

  
