name: Docker login, build & push action
description: Docker composite that does the login into Google AR, builds and pushes the docker image to AR

inputs:
  image:
    required: true
    description: Cloud run service docker image

  service:
    required: true
    description: Cloud run service name

  container:
    required: true
    description: Cloud run service container name

  region:
    required: true
    description: Cloud run service region

  google-login:
    required: true
    description: Perform Google Auth
    default: "true"

  setup-gcloud:
    required: true
    description: Setup GCloud
    default: "false"

  google-credentials:
    required: true
    description: Google Credentials for AR access
    default: ""

outputs:
  image:
    description: Image deployed by this action
    value: ${{ inputs.image }}

runs:
  using: composite
  steps:
  - name: Google Auth
    id: auth
    if: ${{ inputs.google-login == 'true' }}
    uses: 'google-github-actions/auth@v2'
    with:
      token_format: 'access_token'
      credentials_json: '${{ inputs.google-credentials }}'

  - name: 'Set up Cloud SDK'
    if: ${{ inputs.setup-gcloud == 'true' }}
    uses: 'google-github-actions/setup-gcloud@v2'
    with:
      version: '>= 363.0.0'

  - name: Cloud Run Deploy
    shell: bash
    run: gcloud beta run services update '${{ inputs.service }}' --region '${{ inputs.region }}' --container '${{ inputs.container }}' --image '${{ inputs.image }}'
